/** Generated by terminal-relay/scripts/build-agent.mjs; verified before the agent runs the connector. */
export const terminalAgentClientRelease = Object.freeze({"path":"/agent/client-f8faa073f04a1784.mjs","sha256":"f8faa073f04a17843a26d85129044efc0b408bdaab9dbeb5e256fa2be285dcd9"});
