/** Generated by terminal-relay/scripts/build-agent.mjs; verified before the agent runs the connector. */
export const terminalAgentClientRelease = Object.freeze({"path":"/agent/client-25b8bc45c91de9bd.mjs","sha256":"25b8bc45c91de9bdca80e949f6287dc6ba6a3f1c882223c890a724f3cc7d0e7f"});
