/** Generated by terminal-relay/scripts/build-agent.mjs; verified before the agent runs the connector. */
export const terminalAgentClientRelease = Object.freeze({"path":"/agent/client-082fa44f4ae0c47d.mjs","sha256":"082fa44f4ae0c47d0304df742f48883452a5d05e5add0d37f0521a239d94c34d"});
