export { NativeTerminal, NativeTerminal as Terminal, type TerminalViewState } from "./native.js";
export { TerminalCore, type TerminalModes, type CommandMarker, type TerminalActivity } from "./core.js";
export type { TerminalState } from "./state.js";
export { CommandTracker, type CommandRecord } from "./commands.js";
export { TerminalRecorder, replayRecording, type TerminalRecording, type RecordingEvent } from "./recording.js";
export { TerminalSession, type SessionSnapshot, type InputReceipt } from "./session.js";
export { connectTerminalAgent, validateTerminalAgentPairing, handleTerminalAgentRequest, type TerminalAgentOptions, type TerminalAgentRequest } from "./mcp.js";
export { createTerminalAgentInvitation, type TerminalAgentInvitation, type TerminalAgentInvitationOptions, type TerminalAgentClientSource } from "./invitation.js";
export { findInTerminal, terminalTranscript, type TerminalMatch } from "./search.js";
export { encodeTerminalKey, encodeTerminalMouse, encodeTerminalPaste, type TerminalKey, type TerminalMouse } from "./input.js";
export { cellWidth, joinsCell, safeHyperlink } from "./unicode.js";
export { detectTerminalLinks, type DetectedTerminalLink, type TerminalFileReference } from "./links.js";
export type { TerminalFileLinkOptions, TerminalFileResource, TerminalFilePreviewUi, TerminalFilePreviewContext } from "./file-preview.js";
export { terminalThemes, resolveTerminalTheme, type TerminalThemeName, type TerminalThemeChoice } from "./themes.js";
export type { Disposable, TerminalOptions, TerminalSize, TerminalCellMetrics, TerminalTheme, TerminalSurface, ReadableBuffer, ReadableLine, ReadableCell } from "./types.js";
